name: InsultPlayers
version: 1.0-SNAPSHOT
main: me.devdav.insultplayers.InsultPlayers
api-version: 1.16
description: Insult players when they connect with random insults
commands:
  fdp:
    description: "Écrit: \"Je suis un FDP\""